version: '3'

services:
  engine_warvil:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: engine_warvil
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
