export const commands = {
  BASIC_QUESTION: `BASIC_QUESTION`,
  GENERATE_CODE: `GENERATE_CODE`,
  GENERATE_THESIS_TITLE: `GENERATE_THESIS_TITLE`,
  GRAMMAR_CORRECTION: `GRAMMAR_CORRECTION`,
  PARAPHRASE: `PARAPHRASE`,
  SUMMARIZE_FOR_A_STUDENT_GRADE: `SUMMARIZE_FOR_A_STUDENT_GRADE`,
  ENGLISH_TO_OTHER_LANGUAGE: `ENGLISH_TO_OTHER_LANGUAGE`,
  EXPLAIN_PROGRAMMING_CODE: `EXPLAIN_PROGRAMMING_CODE`,
  EVALUATE_A_MATHEMATICAL_EXPRESSION: `EVALUATE_A_MATHEMATICAL_EXPRESSION`,
  CREATE_STUDY_NOTES: `CREATE_STUDY_NOTES`,
};
